bug:
  - '(bug|error|crash|problem|not working|broken)'
enhancement:
  - '(feature|enhancement|improvement|request)'
documentation:
  - '(docs|documentation|readme|guide)'
question:
  - '(question|help|support|how to)'
ui:
  - '(ui|interface|design|look|appearance)'
timestamps:
  - '(timestamp|time|chapter)'
